park/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.urlpatterns import format_suffix_patterns
# from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.welcome),
    path('load_form', views.load_form),
    path('add', views.add),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
    path('search',views.search),
    path('employees',views.EmployeeList.as_view()),
    path('r^(.*)$)', views.welcome),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = views.handler404
# handler500 = views.handler500

myapp/models.py
from django.db import models
class Employee(models.Model):
    eid = models.PositiveIntegerField(unique=True)
    ename = models.CharField(max_length=50)
    eemail = models.EmailField(unique=True)
    econtact = models.PositiveIntegerField(null=True)
    profile_image = models.ImageField(default='default-avatar.png', upload_to="users")

    def __str__(self):
        return self.ename

myapp/forms.py
from django import forms
from .models import Employee
from django.contrib.auth.models import User
from django.core.validators import validate_email
# all the fields

class EmployeeForm(forms.ModelForm):
    # ename=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Employee
        fields = '__all__'
        # fields = ['eid','ename','eemail','econtact','profile_image']
    def clean_eid(self):  # Validates the Computer Name Field
        eid = self.cleaned_data.get('eid')
        if (eid == ""):
            raise forms.ValidationError('This field cannot be left blank')
        return self.cleaned_data['eid']

myapp/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import CreateView
from .models import Employee
from .forms import EmployeeForm
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from .serializers import EmployeeSerializer
from django.contrib import messages
from django.http import HttpResponseRedirect
def welcome(request):
    return render(request, "welcome.html")


def load_form(request):
    form = EmployeeForm
    return render(request, "index.html", {'form': form})

class EmployeeList(APIView):
    def get(self,request):
        employee1=Employee.objects.all()
        serializer=EmployeeSerializer(employee1, many=True)
        return Response(serializer.data)

    def post(selfself):
        pass


def add(request):
    form = EmployeeForm(request.POST or None, request.FILES or None)
    # eid = request.POST['eid']
    # eemail = request.POST['eemail']
    # ename = request.POST['ename']
    # econtact = request.POST['econtact']
    # print("hello eid is "+eid +" ename is "+ename +" eemail is "+ eemail +" econtact is "+ econtact)

    if form.is_valid():
        form.save()
        if request.method == 'POST':
            message = "Thanks for signing "+ "\n" + "your entered name is " + request.POST['ename'] + "\nyour entered id is "+ request.POST['eid']
            email = request.POST['eemail']
            send_mail('Details',
                  message,
                  settings.EMAIL_HOST_USER,
                  [email],
                  fail_silently=False
                  )
    # messages.success(request ,'Data Updated successfully')
        return HttpResponseRedirect('/show')
    else:
        form = EmployeeForm()
        return HttpResponseRedirect("/load_form")

def show(request):
    #showing the details of all the users
    employee = Employee.objects.all
    return render(request, 'show.html', {"employee":employee})


def edit(request, id):   #edit page so that user can edit the page
    employee = Employee.objects.get(id=id)

    return render(request,'edit.html', {'employee':employee})



def update(request, id):
    #update the existing details
    employee = Employee.objects.get(id=id)
    # instance = get_object_or_404(Employee, id=id)
    # form = EmployeeForm(request.POST or None, request.FILES or None, instance=instance)
    file_data = request.FILES or None
    form = EmployeeForm(request.POST,file_data, instance=employee)

    form.save()             #saving the updated form details
    return redirect('/show')



def delete(request, id):   #delete the details
    employee = Employee.objects.get(id=id)   #get the id generated by the database
    employee.delete()
    return redirect('/show')



def search(request):          #search using starting letter of the name
    given_name = request.POST['name']
    employee = Employee.objects.filter(ename__istartswith=given_name)   #using starting alphabets
    return render(request,'show.html',{'employee':employee})

def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)

class EmployeeCreateView(CreateView):   #api generation
    model = Employee
    fields = ('ID', 'NAME', 'EMAIL', 'CONTACT','profile_image')

myapp/templates/base.html
{#{% load cms_tags staticfiles %}#}
<!doctype html>
<html lang="en">
<head>
    <style>
        #loading
        {
            position: fixed;
            width: 100%;
            height: 100vh;
            background: white
            url('https://media.giphy.com/media/f9dfemrLEPRCdJcUED/giphy.gif')
            no-repeat center;
            z-index:999999;

        }

    </style>
  <meta charset="utf-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{#    <link href="{% static 'assets/css/loaders/loader-pulse.css' %}" rel="stylesheet" type="text/css" media="all" />#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">#}
{#  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
{#  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>#}
</head>
<body onload="myFunction()">
<div id="loading"></div>

<div>
{#                    NAVBAR  OF ALL THE PAGES                             #}
  <div class="container" style= "width:100%;margin: auto;">
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
        </li>
      <li class="nav-item active"><a class="nav-link" href="/show">Show All</a></li>
      <li class="nav-item active"><a class="nav-link" href="/load_form">Add New</a></li>
    </ul>
    <form method="POST" action="search" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
      <input name="name" class="form-control mr-sm-2" type="search" placeholder="Search Names" aria-label="Search">
      <button class="btn btn-danger" my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}
    {% endblock %}

</div>
<script>
    var preloader=document.getElementById('loading');
        function myFunction(){
            preloader.style.display='none';
        }

</script>

</body>
</html>

myapp/templates/edit.html
{% extends 'base.html' %}


{%  block content %}


<form method="POST" action="/update/{{ employee.id }}" ><!--using id generated by the database  -->
    {% csrf_token %}

            <label for="eid">ID</label>

            <input name="eid" class="form-control"  aria-describedby="emailHelp" value="{{ employee.eid }}">

               <label for="ename">NAME</label>

               <input name="ename" class="form-control"  aria-describedby="emailHelp" value="{{ employee.ename }}">

                        <label for="eemail">EMAIL-ADDRESS</label>

               <input name="eemail" class="form-control"  aria-describedby="emailHelp" value="{{ employee.eemail }}">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>

                        <label for="econtact">CONTACT</label>

               <input name="econtact" class="form-control"  aria-describedby="emailHelp" value="{{ employee.econtact }}">


            <label for="profile_image">Profile IMAGE</label>

            <img alt="profile image" src= "{{ employee.profile_image.url }}" class="img-responsive" width="150" height="100" >


            <small id="emailHelp" class="form-text text-muted">You cannot change your profile image</small>
               <button type="submit" class="btn btn-primary  btn-block" >Update</button>

</form>
{% endblock %}

myapp/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%  block content %}

{#    <style>#}
{#    .form-control.success i.fa-check-circle {#}
{#	color: #2ecc71;#}
{#	visibility: visible;#}
{#}#}
{##}
{#.form-control.error i.fa-exclamation-circle {#}
{#	color: #e74c3c;#}
{#	visibility: visible;#}
{#}#}
{#    .form-control i {#}
{#	visibility: hidden;#}
{#	position: absolute;#}
{#	top: 40px;#}
{#	right: 10px;#}
{#}#}
{#    </style>#}
{#    <style>#}
{#        #loading#}
{#        {#}
{#            position: fixed;#}
{#            width: 100%;#}
{#            height: 100vh;#}
{#            background: white#}
{#            url('https://media.giphy.com/media/WiIuC6fAOoXD2/giphy.gif')#}
{#            no-repeat center;#}
{##}
{##}
{#        }#}
{#    </style>#}
{#    <div id="loading"></div>#}
<div class="container">

{#        <div class="form-group">   <!-- for alert box  -->#}
{#        {% if messages %}#}
{#        <ul class="messages">#}
{#        {% for message in messages %}#}
{#        <li>#}
{#            <div class="alert alert-success">{{ message }}#}
{#            </div>#}
{#        </li>#}
{#        {% endfor %}#}
{#        </ul>#}
{#        {% endif %}#}
{#        </div>#}

            <form method="POST" action="/add" id="form" enctype="multipart/form-data" class="form">    <!-- adding the details in the form  -->
                {% csrf_token %}
{#                 <div class="form-group">#}
{#            <label for="eid">Id</label>#}
{#            <input type="number" name="eid" class="form-control" id="eid" aria-describedby="emailHelp" placeholder="Id" >#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="ename">Name</label>#}
{#            <input type="text" class="form-control" id="ename" placeholder="Name" >#}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="eemail">EMAIL</label>#}
{#            <input type="email" class="form-control" id="eemail" placeholder="Email" >#}
{#          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>#}
{##}
{#          </div>#}
{#          <div class="form-group">#}
{#            <label for="econtact">Contact Details</label>#}
{#            <input type="number" class="form-control" id="econtact" placeholder="Name" >#}
{#          </div>#}
{#            <div class="form-group">#}
{#            <label for="image">Profile Image</label>#}
{#            <input type="file" class="form-control" id="profile_image"  required>#}
{#          </div>#}

                <div class="container">
                    <div id="div_id_eid" class="form-group">
                <label for="eid" class=" requiredField"> ID  </label>
                <div class=""><input type="number" name="eid" id="eid" min="0" class="numberinput form-control" >
                    </div>

                 </div>


                <div id="div_id_ename" class="form-group">
            <label for="id_ename" class=" requiredField">NAME</label>
                    <div class="">
                    <input type="text" name="ename" id="ename" maxlength="50" class="textinput textInput form-control"  >
                    </div></div>



{#                    {{ form.ename|as_crispy_field }}#}
{#                    {{ form.eemail|as_crispy_field }}#}

                    <div id="div_id_eemail" class="form-group">
                <label for="id_eemail" class=" requiredField">Email Address</label>
                        <div class="">
                            <input type="email" name="eemail" maxlength="254" class="emailinput form-control"  id="eemail">
                        </div></div>

                    <small id="emailHelp"  style="color:red;">We'll never share your email with anyone else.</small>
                    <div>&nbsp</div>



{#                    {{ form.econtact|as_crispy_field }}#}
                    <div id="div_id_econtact" class="form-group">
            <label for="econtact" class=" requiredField">Contact Details</label>
                        <div class="">
                            <input type="number"  name="econtact" min="0" class="numberinput form-control" id="econtact">
                        </div></div>


{##}
                    {{ form.profile_image|as_crispy_field }}
                    <small id="profileImageHelp"  style="color:red;">Image should be less than 100kb</small>
{##}
{#                </div>#}
                <button type="submit" id="submit" class="btn btn-primary btn-block" >ADD</button>

            </form>
            </div>


    {#        {% endif %}#}
    </div>          <!-- end alert box div -->

{#<script>#}
{#   document.getElementById("submit").addEventListener("click", display);#}
{#    function display(){#}
        {#alert("hello");#}
        {#swal("Hello world!");#}
{#        alert("form.eid")#}
    {#swal("Good job!", "You clicked the button!", "success");#}
{##}
{#    }#}
{##}
{##}
{#    </script>#}

    <script>
    const form = document.getElementById('form');
    const ename = document.getElementById('ename');
    const eemail = document.getElementById('eemail');
    const econtact = document.getElementById('econtact');
    const eid = document.getElementById('eid');
form.addEventListener('submit', e => {
	{#e.preventDefault();#}
	checkInputs();
        Default();
});
function checkInputs() {
    // trim to remove the whitespaces

    const enameValue = ename.value.trim();
    const eemailValue = eemail.value.trim();
    const econtactValue = econtact.value.trim();
    const eidValue=eid.value.trim();
    var digits = econtactValue.toString().length;
   if(enameValue === '' || eemailValue==='' || econtactValue==='' || eidValue===''  ) {

            alert("Please fill the details");
         {#location.reload();#}
	}
   else if(digits<10 || digits>10){

       swal({
           icon:"error",
           text:"Phone number must be of 10 digits in India,You can change it in edit option",
           timer:10000
       })

   }
   else
   {
      swal({
          title: "Submitting Form",
          text: "Your form is submitting, Please wait a while",
          icon: "success",
            buttons: false,
            timer:10000
        });
   }





}

    </script>

{% endblock %}

myapp/templates/show.html
{% extends 'base.html' %}

{%  block content %}
{#        internal css used to match with navbar  #}
{#    <style>#}
{#    table {#}
{#      width: 100%;#}
{#      border-collapse: collapse;#}
{#    }#}
{#    /* Zebra striping */#}
{#    tr:nth-of-type(odd) {#}
      {#background: #eee;#}
{#    }#}
{#    th {#}
      {#background: #333;#}
      {#color: white;#}
      {#font-weight: bold;#}
{#    }#}
{#    td, th {#}
{#      padding: 6px;#}
      {#border: 1px solid #ccc;#}
      {#text-align: left;#}
{#    }#}
{#    </style>   <!--ending css  -->#}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">#}
{#  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
{#  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>#}
    <div class="container">
<table class="table table-hover " >
  <thead >
    <tr>
        <th>IMAGE</th>
        <th>ID</th>
        <th>NAME</th>
        <th>EMAIL</th>
        <th>CONTACT</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
  </thead>
    {% for i in employee %} <!--  looping through all the data -->
    <tr>
    <td>
     <div>
{#         <h1>first ->"{{ instance.image }}"</h1>#}
         {#         <h1>1-> "{{ i.profile_image.url }}"</h1>#}
         {#         <h1>2 -> "{{ i.instance.image }}"</h1>#}
{#         <h5>{{ i.profile_image.url }}</h5>#}
{#         <img src="{% static "{{ i.profile_image.url }}" %}" alt="My image">#}
{#         <h1>{{ MEDIA_URL }}</h1>#}
    <img src= "{{ i.profile_image.url }}" class="img-responsive" width="150" height="100" >
    </div>
    </td>
        <td>{{ i.eid }}</td>
        <td>{{ i.ename }}</td>
        <td>{{ i.eemail }}</td>
        <td>{{ i.econtact}}</td>
        <td><a href="edit/{{ i.id }}">Edit</a>
        <td><a href="delete/{{ i.id }}">Delete</a>
    </tr>
    {% endfor %}

</table>
    </div>
{% endblock %}

myapp/templates/welcome.html
{% extends 'base.html' %}
{%  block content %}

    <div>&nbsp</div><div>&nbsp</div>

    <p class="h5"><a href="/load_form" >Add New </a></p><div>&nbsp</div>
    <p class="h5" ><a href="/show">Show </a></p>

{% endblock %}

</html>